on: [pull_request]

permissions:
  actions: write

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Local cache
      uses: actions/cache@v4
      with:
        path: /nix/store
        key: "${{ runner.os }}-nix-cache"
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v15
      with:
        name: jappie
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build nix/ci.nix
    - run: nix-shell --run "echo OK"
    - name: Cancel workflow on failure
      if: failure()
      continue-on-error: true
      run: gh run cancel ${{ github.run_id }}
      env:
        GH_TOKEN: ${{ github.token }}

  cabal:
    runs-on: ${{ matrix.sys.os }}

    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    strategy:
      fail-fast: true
      matrix:
        ghc:
          - '9.12'
          - '9.10'
          - '9.8'
          - '9.6'
        sys:
          - { os: ubuntu-latest, shell: bash }
          - { os: macOS-latest, shell: bash }
          - { os: windows-latest, shell: "C:/msys64/usr/bin/bash.exe -e {0}" }

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Set LD_LIBRARY_PATH (Linux)
      if: runner.os == 'Linux'
      run: echo "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Install pkg-config (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1" >> $GITHUB_ENV
        echo "PKG_CONFIG_ALLOW_SYSTEM_LIBS=1"   >> $GITHUB_ENV
        ghcup run -m -- pacman --noconfirm -S mingw-w64-x86_64-pkg-config
        echo "C:/msys64/mingw64/bin" >> "$GITHUB_PATH"

    - name: Setup Botan
      uses: haskell-cryptography/botan/.github/actions/setup-botan@main
      with:
        botan-version: "3.10.0"

    - name: Cabal cache
      uses: actions/cache@v4
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Cabal update
      run: cabal update
    - name: Build using cabal
      run: |
        cabal build all \
          --extra-include-dirs=${{ runner.os == 'Windows' && 'C:/msys64/mingw64/include' || '/usr/local/include' }} \
          --extra-lib-dirs=${{ runner.os == 'Windows' && 'C:/msys64/mingw64/lib' || '/usr/local/lib' }} \
          ${{ runner.os == 'Windows' && '--extra-prog-path=C:/msys64/mingw64/bin' || '' }}
    - name: Test
      run: |
        cabal test test \
          --extra-include-dirs=${{ runner.os == 'Windows' && 'C:/msys64/mingw64/include' || '/usr/local/include' }} \
          --extra-lib-dirs=${{ runner.os == 'Windows' && 'C:/msys64/mingw64/lib' || '/usr/local/lib' }} \
          ${{ runner.os == 'Windows' && '--extra-prog-path=C:/msys64/mingw64/bin' || '' }}
    - name: Cancel workflow on failure
      if: failure()
      continue-on-error: true
      run: gh run cancel ${{ github.run_id }}
      env:
        GH_TOKEN: ${{ github.token }}
